language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: linux
      env: MASON_PLATFORM=linux
      sudo: false
      addons:
        apt:
          packages: [ 'm4', 'flex' ]

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
